"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


def env_bool(name, default=False):
    return os.environ.get(name, str(default)) in ('1', 'true', 'True')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'dev-secret-key-change-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DEBUG', False)

ALLOWED_HOSTS = [
    h.strip() for h in os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if h.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'simulation',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',
    'http://127.0.0.1:5173',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = 'config.asgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases
#
# DATABASE_ENGINE=sqlite switches to SQLite for single-machine deployments
# (see docs/DEPLOYMENT.md) — the schema has no Postgres-specific features, so
# this is a safe swap. Local dev is unaffected: this var is unset there, so
# it falls through to the existing Postgres/Docker Compose setup.

if os.environ.get('DATABASE_ENGINE') == 'sqlite':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('POSTGRES_DB', 'mapviz'),
            'USER': os.environ.get('POSTGRES_USER', 'mapviz'),
            'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'mapviz'),
            'HOST': os.environ.get('POSTGRES_HOST', 'localhost'),
            'PORT': os.environ.get('POSTGRES_PORT', '5432'),
        }
    }


# Simulation configuration
# See docs/Design Analysis.md §4 for the reasoning behind these defaults.

SIMULATION = {
    'INGEST_API_KEY': os.environ.get('INGEST_API_KEY', 'dev-ingest-key'),
    'BASE_STATION_LAT': float(os.environ.get('BASE_STATION_LAT', '37.7749')),
    'BASE_STATION_LNG': float(os.environ.get('BASE_STATION_LNG', '-122.4194')),
    'RADIUS_KM': float(os.environ.get('SIMULATION_RADIUS_KM', '100')),
    'SEED': int(os.environ.get('SIMULATION_SEED', '42')),
    'AIRCRAFT_COUNT': int(os.environ.get('AIRCRAFT_COUNT', '150')),
    'TICK_INTERVAL_MS': int(os.environ.get('TICK_INTERVAL_MS', '200')),
    'NEAREST_ZONES_COUNT': int(os.environ.get('NEAREST_ZONES_COUNT', '3')),
    'WARNING_TTE_SECONDS': float(os.environ.get('WARNING_TTE_SECONDS', '60')),
    'HISTORY_WINDOW_SECONDS': float(os.environ.get('HISTORY_WINDOW_SECONDS', '300')),
    'DRONE_COUNT': int(os.environ.get('DRONE_COUNT', '10')),
    'DRONE_MAX_SPEED_MPS': float(os.environ.get('DRONE_MAX_SPEED_MPS', '320')),
    'DRONE_MAX_TURN_RATE_DEG_S': float(os.environ.get('DRONE_MAX_TURN_RATE_DEG_S', '6')),
    'DRONE_HOLD_DISTANCE_M': float(os.environ.get('DRONE_HOLD_DISTANCE_M', '200')),
    'DRONE_MAX_MONITOR_SECONDS': float(os.environ.get('DRONE_MAX_MONITOR_SECONDS', '120')),
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
