# Generated by Django 6.1 on 2026-08-27 03:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatrolPath',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coordinates', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RestrictedZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('coordinates', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TelemetrySample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft_id', models.CharField(db_index=True, max_length=64)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('altitude_m', models.FloatField()),
                ('heading_deg', models.FloatField()),
                ('speed_mps', models.FloatField()),
            ],
            options={
                'indexes': [models.Index(fields=['aircraft_id', 'timestamp'], name='simulation__aircraf_7dd2a5_idx')],
            },
        ),
    ]
